<Project>
  <PropertyGroup>
    <ProjectName>CasualtiesTogetherWhisper</ProjectName>
    <BaseGamePath>D:\Programs\Steam\steamapps\common\Casualties Unknown Demo</BaseGamePath>
    <BepInExDir>$(BaseGamePath)/BepInEx</BepInExDir>
    <GameAssembliesDir>$(BaseGamePath)/CasualtiesUnknown_Data/Managed</GameAssembliesDir>
  </PropertyGroup>
</Project>
